version: '3'
services:
  movarisch-app:
    build: .
    ports:
      - "8004:80"
    restart: always
    container_name: movarisch-app
    depends_on:
      - movarisch-backend

  movarisch-backend:
    build: ./server
    ports:
      - "3000:3000"
    restart: always
    container_name: movarisch-backend
    volumes:
      - ./server/movarisch.db:/app/movarisch.db
